/**
 * Log-mode compaction.
 *
 * In log mode compaction never rewrites history. When the context policy
 * asks for it, the call declares a `compaction` transition that creates a
 * child of the head's version, and the call's own prepare commits it before
 * the compacted context is first sent:
 *
 * ```
 *   child path = parent's leading runtime prefix (inherited, unchanged)
 *              + the summary
 *              + the retained tail (re-appended unchanged, in path order)
 *              + the call's new input
 * ```
 *
 * - Runtime context is never summarised, like the legacy prompt-builder
 *   context it replaces: the context manager sees every active
 *   `runtime_context` entry as a system message, which it always keeps. The
 *   leading run of them is the prefix the child inherits (a version
 *   inherits a leading entry count); the rest are part of the retained tail.
 * - Retained entries are re-appended with their own keys and content, so
 *   assistant reasoning and provider options survive byte for byte, and a
 *   store that keeps content by digest stores no second copy. A
 *   `supersedes` whose target is no longer on the child's path is dropped
 *   (the entry is then the slot's current value); a retraction of such a
 *   target is dropped with it.
 * - A tool call and its result stay together: a child that keeps one
 *   without the other is refused.
 * - The summary is new content: it passes the PreGenerate screening
 *   (redaction, guardrails) before it is committed.
 * - The summary is generated by the context manager's `summarizer`, on the
 *   summary stream the compaction names, never on the compacted stream.
 *
 * Later calls append to the child, so they reuse the summary instead of
 * summarising again.
 *
 * @packageDocumentation
 * @internal
 */

import type { ModelMessage } from "ai";
import { ContextLogInvalidError } from "../context-log/errors.js";
import { canonicalContextJson } from "../context-log/json.js";
import { activeContextEntries } from "../context-log/supersession.js";
import type {
  ContextEntryInput,
  ContextHead,
  ContextStreamRef,
  ContextTransition,
  RuntimeContextEntryInput,
} from "../context-log/types.js";
import type { CompactionContextLog, CompactOptions } from "../context-manager.js";
import type { GenerateOptions } from "../types.js";
import { sha256Hex } from "./log-boundary.js";
import type { MessageRuntime } from "./messages.js";

/**
 * What a log-mode call needs to compact the path it was planned from.
 *
 * @internal
 */
export interface LogCompactionInput {
  stream: ContextStreamRef;
  /** The head `path` was read at. */
  head: ContextHead;
  /** The head version's frozen core; the child keeps it. */
  core: string;
  /** The contract the call is projected under; the child records it. */
  contract: Readonly<Record<string, string>>;
  /** Content of the committed path at `head`, in position order. */
  path: readonly ContextEntryInput[];
  /**
   * The call's new, already screened entries that follow the path and are
   * not committed yet. They are always kept, after the retained tail.
   */
  pending: readonly ContextEntryInput[];
  /** Prefix for the summary entries' keys. Unique for the call. */
  keyPrefix: string;
  /** The call's options, for the run id and the compaction hooks. */
  options: GenerateOptions;
  /** Screens new entries (the summary) before they are committed. */
  screen: (entries: ContextEntryInput[]) => Promise<ContextEntryInput[]>;
}

/**
 * A planned compaction: the transition and entries the call's prepare
 * commits.
 *
 * @internal
 */
export interface LogCompaction {
  /** The `compaction` transition to the child version. */
  transition: ContextTransition;
  /** Entries to append after the inherited prefix: summary, retained tail, new input. */
  append: ContextEntryInput[];
  /** Content of the child's path once committed: the inherited prefix, then `append`. */
  entries: ContextEntryInput[];
}

/**
 * Plans a compaction of a log-mode call's path, or returns `undefined` when
 * the context policy does not ask for one.
 *
 * @internal
 */
export type LogCompactor = (input: LogCompactionInput) => Promise<LogCompaction | undefined>;

/**
 * Where a message of the compaction view came from: the core, a runtime
 * context entry of the path (always kept), a conversation entry of the path
 * (kept or summarised), or the call's new input (always kept).
 */
type ViewSource =
  | { kind: "core" }
  | { kind: "runtime"; index: number }
  | { kind: "path"; index: number }
  | { kind: "pending"; index: number };

/** Text a runtime context entry is shown to the context manager as. */
function runtimeText(entry: RuntimeContextEntryInput): string {
  return typeof entry.payload === "string" ? entry.payload : canonicalContextJson(entry.payload);
}

/** An entry as the context manager sees it: runtime context as a system message. */
function viewMessage(entry: ContextEntryInput): ModelMessage {
  if (entry.kind === "runtime_context") {
    return { role: "system", content: runtimeText(entry) };
  }
  return entry.message;
}

/** Tool call ids of the calls and results an entry carries. */
function toolIds(entry: ContextEntryInput): { calls: string[]; results: string[] } {
  if (entry.kind === "assistant" && Array.isArray(entry.message.content)) {
    const calls = entry.message.content.flatMap((part) =>
      part.type === "tool-call" ? [part.toolCallId] : [],
    );
    return { calls, results: [] };
  }
  if (entry.kind === "tool_result") {
    const results = entry.message.content.flatMap((part) =>
      part.type === "tool-result" ? [part.toolCallId] : [],
    );
    return { calls: [], results };
  }
  return { calls: [], results: [] };
}

/** Every tool call id with a call, and with a result, in a list of entries. */
function toolPairs(entries: readonly ContextEntryInput[]): {
  calls: Set<string>;
  results: Set<string>;
} {
  const calls = new Set<string>();
  const results = new Set<string>();
  for (const entry of entries) {
    const ids = toolIds(entry);
    for (const id of ids.calls) calls.add(id);
    for (const id of ids.results) results.add(id);
  }
  return { calls, results };
}

/**
 * Refuses a child that keeps a tool call without the result the parent had
 * for it, or a result without its call.
 */
function assertToolPairsKept(
  parent: readonly ContextEntryInput[],
  child: readonly ContextEntryInput[],
): void {
  const before = toolPairs(parent);
  const after = toolPairs(child);
  for (const id of after.calls) {
    if (before.results.has(id) && !after.results.has(id)) {
      throw new ContextLogInvalidError(
        "compaction_split_tool_call",
        `Compaction kept tool call "${id}" without its result`,
      );
    }
  }
  for (const id of after.results) {
    if (before.calls.has(id) && !after.calls.has(id)) {
      throw new ContextLogInvalidError(
        "compaction_split_tool_call",
        `Compaction kept the result of tool call "${id}" without the call`,
      );
    }
  }
}

/**
 * Re-appended entries in order, with every `supersedes` that no longer has
 * a target on the child's path dropped (and any retraction of one removed).
 */
function rebaseSupersession(
  inherited: readonly ContextEntryInput[],
  entries: readonly ContextEntryInput[],
): ContextEntryInput[] {
  const onPath = new Set(inherited.map((entry) => entry.key));
  const rebased: ContextEntryInput[] = [];
  for (const entry of entries) {
    if (
      entry.kind === "runtime_context" &&
      entry.supersedes !== undefined &&
      !onPath.has(entry.supersedes)
    ) {
      if (entry.retraction === true) continue;
      const { supersedes: _target, ...current } = entry;
      rebased.push(current);
    } else {
      rebased.push(entry);
    }
    onPath.add(entry.key);
  }
  return rebased;
}

/**
 * Maps each message the context manager returned to the view message it
 * keeps, or `undefined` for a new message (the summary).
 *
 * Kept messages are matched by identity, as the built-in manager returns
 * them. Only a manager that kept none by identity (one that copies what it
 * keeps) is matched by content; otherwise a summary whose text equals an
 * earlier message, such as a previous summary, would be taken as kept.
 */
function mapKept(
  view: readonly ModelMessage[],
  kept: readonly ModelMessage[],
): Array<number | undefined> {
  const byIdentity = new Map<ModelMessage, number>();
  view.forEach((message, index) => {
    byIdentity.set(message, index);
  });
  const identical = kept.map((message) => byIdentity.get(message));
  if (identical.some((index) => index !== undefined)) {
    return identical;
  }
  const canonicalView = view.map((viewed) => canonicalContextJson(viewed));
  const used = new Set<number>();
  return kept.map((message) => {
    const canonical = canonicalContextJson(message);
    const found = canonicalView.findIndex((viewed, at) => !used.has(at) && viewed === canonical);
    if (found === -1) return undefined;
    used.add(found);
    return found;
  });
}

/**
 * Creates the log-mode compactor for an agent with a context manager.
 *
 * @internal
 */
export function createLogCompactor(
  compactIfNeeded: MessageRuntime["compactMessagesIfNeeded"],
): LogCompactor {
  return async (input) => {
    const { stream, head, core, path, pending, options } = input;
    if (path.length === 0 || options._skipCompaction) {
      return undefined;
    }

    // The leading run of active runtime context is the unchanged prefix the
    // child inherits. The manager sees it (and the core) as system
    // messages, which it always keeps and never summarises.
    const active = new Set<ContextEntryInput>(activeContextEntries([...path, ...pending]));
    let inheritedCount = 0;
    while (
      inheritedCount < path.length &&
      path[inheritedCount]!.kind === "runtime_context" &&
      active.has(path[inheritedCount]!)
    ) {
      inheritedCount += 1;
    }

    const view: ModelMessage[] = [];
    const sources: ViewSource[] = [];
    if (core !== "") {
      view.push({ role: "system", content: core });
      sources.push({ kind: "core" });
    }
    path.forEach((entry, index) => {
      if (active.has(entry)) {
        view.push(viewMessage(entry));
        sources.push({ kind: entry.kind === "runtime_context" ? "runtime" : "path", index });
      }
    });
    pending.forEach((entry, index) => {
      if (active.has(entry)) {
        view.push(viewMessage(entry));
        sources.push({ kind: "pending", index });
      }
    });

    const runId = options._runId ?? "run";
    // The head's path is immutable, so its reference and the new input
    // identify the source exactly.
    const sourceDigest = sha256Hex(
      canonicalContextJson({
        versionId: head.versionId,
        entryCount: head.entryCount,
        pending: [...pending],
      }),
    );
    const contextLog: CompactionContextLog = {
      runId,
      stream,
      sourceDigest,
      summaryStream: {
        threadId: stream.threadId,
        branchId: stream.branchId,
        streamId: `${runId}/summary/${sourceDigest}`,
      },
    };
    const compactOptions: CompactOptions = { contextLog };
    const outcome = await compactIfNeeded(view, options, stream.threadId, compactOptions);
    if (!outcome.compacted) {
      return undefined;
    }

    // The conversation entries the manager kept, and the new messages it
    // returned (the summary). The runtime places everything: the prefix,
    // then the summary, then the kept entries in path order, then the new
    // input.
    const summary: ContextEntryInput[] = [];
    const retained = new Set<number>();
    mapKept(view, outcome.messages).forEach((viewIndex, at) => {
      if (viewIndex !== undefined) {
        const source = sources[viewIndex]!;
        if (source.kind === "path") retained.add(source.index);
        return;
      }
      const message = outcome.messages[at]!;
      const key = `${input.keyPrefix}:summary:${summary.length}`;
      if (message.role === "assistant") {
        summary.push({ kind: "assistant", key, message });
      } else if (message.role === "user") {
        summary.push({ kind: "user", key, message });
      } else {
        throw new ContextLogInvalidError(
          "compaction_invalid_summary",
          `Compaction produced a new "${message.role}" message; a summary must be a user or assistant message`,
        );
      }
    });

    const compactable = sources.filter((source) => source.kind === "path").length;
    if (summary.length === 0 && retained.size === compactable) {
      // Nothing was summarised: the head's version stays current.
      return undefined;
    }

    // The summary is new content: screen it like any other new input.
    const screened = summary.length > 0 ? await input.screen(summary) : [];
    if (
      screened.length !== summary.length ||
      screened.some((entry, index) => entry.kind !== summary[index]!.kind)
    ) {
      throw new ContextLogInvalidError(
        "compaction_invalid_summary",
        "Screening the compaction summary must keep its entries",
      );
    }
    const tail = path.filter(
      (entry, index) =>
        index >= inheritedCount &&
        active.has(entry) &&
        (entry.kind === "runtime_context" || retained.has(index)),
    );

    const prefix = path.slice(0, inheritedCount);
    const append = rebaseSupersession(prefix, [...screened, ...tail, ...pending]);
    const entries = [...prefix, ...append];
    assertToolPairsKept([...path, ...pending], entries);

    return {
      transition: {
        reason: "compaction",
        parent: { versionId: head.versionId, inheritedCount },
        core,
        contract: { ...input.contract },
      },
      append,
      entries,
    };
  };
}
