/**
 * Log-mode compaction.
 *
 * In log mode compaction never rewrites history. When the context policy
 * asks for it, the call declares a `compaction` transition that creates a
 * child of the head's version, and the call's own prepare commits it before
 * the compacted context is first sent:
 *
 * ```
 *   child path = parent's leading runtime prefix (inherited, unchanged)
 *              + the summary
 *              + the retained tail (re-appended unchanged, in path order)
 *              + the call's new input
 * ```
 *
 * - Runtime context is never summarised, like the legacy prompt-builder
 *   context it replaces: the context manager sees every active
 *   `runtime_context` entry as a system message, which it always keeps. The
 *   leading run of them is the prefix the child inherits (a version
 *   inherits a leading entry count); the rest are part of the retained tail.
 * - Retained entries are re-appended with their own keys and content, so
 *   assistant reasoning and provider options survive byte for byte, and a
 *   store that keeps content by digest stores no second copy. A
 *   `supersedes` whose target is no longer on the child's path is dropped
 *   (the entry is then the slot's current value); a retraction of such a
 *   target is dropped with it.
 * - A tool call, its approval request, its resolution and its result stay
 *   together: when the manager keeps any of them, all are kept, and a child
 *   that still splits them is refused.
 * - Under append-only supersession (a contract with `supersession: "append"`)
 *   the request carries every superseded entry and retraction, so the
 *   manager is shown them too, as system messages it counts but never
 *   summarises. The child drops them: compaction is the only place they
 *   leave the request. When the manager keeps every conversation entry, a
 *   child without a summary that only drops them is still progress, but
 *   only when it brings the request back under budget (otherwise it would
 *   be declared again on every turn).
 * - The budget is counted on the request the model would be sent: the
 *   call's adapter projection of the path and new input, with its update
 *   labels, retraction notices and any host rendering (LLE-14056). The
 *   view above is only what the manager keeps or summarises.
 * - Nothing is compacted while a call waits for its interrupt's resolution.
 * - The summary is new content: it passes the PreGenerate screening
 *   (redaction, guardrails) before it is committed.
 * - The summary is generated by the context manager's `summarizer`, on the
 *   summary stream the compaction names, never on the compacted stream.
 *
 * Later calls append to the child, so they reuse the summary instead of
 * summarising again.
 *
 * @packageDocumentation
 * @internal
 */

import type { ModelMessage } from "ai";
import { ContextLogConflictError, ContextLogInvalidError } from "../context-log/errors.js";
import { canonicalContextJson } from "../context-log/json.js";
import { appendOnlyRuntimeTexts, SUPERSESSION_CONTRACT_KEY } from "../context-log/projection.js";
import { activeContextEntries } from "../context-log/supersession.js";
import type {
  ContextEntryInput,
  ContextHead,
  ContextStreamRef,
  ContextTransition,
  RuntimeContextEntryInput,
} from "../context-log/types.js";
import type { CompactionContextLog, CompactOptions } from "../context-manager.js";
import type { GenerateOptions } from "../types.js";
import { sha256Hex } from "./log-boundary.js";
import { findUnresolvedInterrupts } from "./log-interrupts.js";
import type { MessageRuntime } from "./messages.js";

/**
 * What a log-mode call needs to compact the path it was planned from.
 *
 * @internal
 */
export interface LogCompactionInput {
  stream: ContextStreamRef;
  /** The head `path` was read at. */
  head: ContextHead;
  /** The head version's frozen core; the child keeps it. */
  core: string;
  /** The contract the call is projected under; the child records it. */
  contract: Readonly<Record<string, string>>;
  /** Content of the committed path at `head`, in position order. */
  path: readonly ContextEntryInput[];
  /**
   * The call's new, already screened entries that follow the path and are
   * not committed yet. They are always kept, after the retained tail.
   */
  pending: readonly ContextEntryInput[];
  /** Prefix for the summary entries' keys. Unique for the call. */
  keyPrefix: string;
  /** The call's options, for the run id and the compaction hooks. */
  options: GenerateOptions;
  /** Screens new entries (the summary) before they are committed. */
  screen: (entries: ContextEntryInput[]) => Promise<ContextEntryInput[]>;
  /**
   * Projects entries with the call's adapter, core, contract and target:
   * the messages the model would be sent. The budget is counted on them
   * (LLE-14056), so update labels, retraction notices and a host adapter's
   * own rendering are budgeted exactly.
   */
  project: (entries: readonly ContextEntryInput[]) => Promise<ModelMessage[]>;
}

/**
 * A planned compaction: the transition and entries the call's prepare
 * commits.
 *
 * @internal
 */
export interface LogCompaction {
  /** The `compaction` transition to the child version. */
  transition: ContextTransition;
  /** Entries to append after the inherited prefix: summary, retained tail, new input. */
  append: ContextEntryInput[];
  /** Content of the child's path once committed: the inherited prefix, then `append`. */
  entries: ContextEntryInput[];
}

/**
 * Plans a compaction of a log-mode call's path, or returns `undefined` when
 * the context policy does not ask for one.
 *
 * @internal
 */
export type LogCompactor = (input: LogCompactionInput) => Promise<LogCompaction | undefined>;

/**
 * Where a message of the compaction view came from: the core, a superseded
 * runtime context entry or retraction the request still carries (counted,
 * never kept), a runtime context entry of the path (always kept), a
 * conversation entry of the path (kept or summarised), or the call's new
 * input (always kept).
 */
type ViewSource =
  | { kind: "core" }
  | { kind: "superseded" }
  | { kind: "runtime"; index: number }
  | { kind: "path"; index: number; resolution?: number }
  | { kind: "pending"; index: number };

/** Text a runtime context entry is shown to the context manager as. */
function runtimeText(entry: RuntimeContextEntryInput): string {
  return typeof entry.payload === "string" ? entry.payload : canonicalContextJson(entry.payload);
}

/** An entry as the context manager sees it: runtime context as a system message. */
function viewMessage(entry: ContextEntryInput): ModelMessage {
  if (entry.kind === "runtime_context") {
    return { role: "system", content: runtimeText(entry) };
  }
  return entry.message;
}

/** The approval ids a resolution-only `tool_result` entry answers, or none. */
function resolutionApprovals(entry: ContextEntryInput): string[] {
  if (entry.kind !== "tool_result") return [];
  const parts = partsOf(entry);
  if (parts.length === 0 || parts.some((part) => part.type !== "tool-approval-response")) {
    return [];
  }
  return parts.flatMap((part) => (typeof part.approvalId === "string" ? [part.approvalId] : []));
}

/**
 * Pairs each approval resolution with the result that directly follows it
 * for the same call, by path index (resolution to result).
 *
 * The manager is shown such a pair as one tool message, the resolution's
 * parts then the result's. The built-in retention treats a call and the
 * result messages after it as one block, and a resolution alone carries no
 * result, so it would cut the block between them; shown with its result,
 * the call, the resolution and the result are kept or summarised together,
 * and the pair counts once, as the real result it is, against the manager's
 * tool-result quota.
 */
function pairResolutions(
  path: readonly ContextEntryInput[],
  active: ReadonlySet<ContextEntryInput>,
): Map<number, number> {
  const approvals = new Map<string, string>();
  for (const entry of path) {
    for (const part of partsOf(entry)) {
      if (
        part.type === "tool-approval-request" &&
        typeof part.approvalId === "string" &&
        typeof part.toolCallId === "string"
      ) {
        approvals.set(part.approvalId, part.toolCallId);
      }
    }
  }
  const pairs = new Map<number, number>();
  path.forEach((entry, index) => {
    const next = path[index + 1];
    if (!active.has(entry) || next === undefined || next.kind !== "tool_result") return;
    const calls = new Set(resolutionApprovals(entry).map((id) => approvals.get(id)));
    const answers = partsOf(next).some(
      (part) => part.type === "tool-result" && calls.has(part.toolCallId as string),
    );
    if (answers) pairs.set(index, index + 1);
  });
  return pairs;
}

/** A message part as far as tool grouping needs it. */
type ToolPart = { type: string; toolCallId?: unknown; approvalId?: unknown; toolName?: unknown };

/** The parts of an entry's message, or none for runtime context and text. */
function partsOf(entry: ContextEntryInput): readonly ToolPart[] {
  if (entry.kind === "runtime_context" || typeof entry.message.content === "string") {
    return [];
  }
  return entry.message.content as readonly ToolPart[];
}

/**
 * The tool group of each entry: entries that share a tool call, directly or
 * through an approval (the request names the call, the response only its
 * approval id), are one group, so a call, its approval request, its
 * resolution and its result are kept or summarised together. `undefined`
 * for an entry without tool parts.
 */
function toolGroups(entries: readonly ContextEntryInput[]): Array<number | undefined> {
  const approvals = new Map<string, string>();
  for (const entry of entries) {
    for (const part of partsOf(entry)) {
      if (
        part.type === "tool-approval-request" &&
        typeof part.approvalId === "string" &&
        typeof part.toolCallId === "string"
      ) {
        approvals.set(part.approvalId, part.toolCallId);
      }
    }
  }
  const parent = entries.map((_entry, index) => index);
  const root = (index: number): number => {
    let current = index;
    while (parent[current] !== current) current = parent[current]!;
    return current;
  };
  const owner = new Map<string, number>();
  const grouped = new Set<number>();
  entries.forEach((entry, index) => {
    for (const part of partsOf(entry)) {
      let id: string | undefined;
      if (part.type === "tool-approval-response" && typeof part.approvalId === "string") {
        id = approvals.get(part.approvalId) ?? `approval:${part.approvalId}`;
      } else if (part.type.startsWith("tool-") && typeof part.toolCallId === "string") {
        id = part.toolCallId;
      }
      if (id === undefined) continue;
      grouped.add(index);
      const first = owner.get(id);
      if (first === undefined) owner.set(id, index);
      else parent[root(index)] = root(first);
    }
  });
  return entries.map((_entry, index) => (grouped.has(index) ? root(index) : undefined));
}

/**
 * Refuses a child that keeps part of a tool group without the rest: a call
 * without its result, approval request, resolution, or the reverse.
 */
function assertToolGroupsKept(
  parent: readonly ContextEntryInput[],
  child: readonly ContextEntryInput[],
): void {
  const kept = new Set(child.map((entry) => entry.key));
  const members = new Map<number, ContextEntryInput[]>();
  toolGroups(parent).forEach((group, index) => {
    if (group === undefined) return;
    members.set(group, [...(members.get(group) ?? []), parent[index]!]);
  });
  for (const group of members.values()) {
    const keptCount = group.filter((entry) => kept.has(entry.key)).length;
    if (keptCount > 0 && keptCount < group.length) {
      throw new ContextLogInvalidError(
        "compaction_split_tool_call",
        `Compaction kept part of a tool call (${group.map((entry) => entry.key).join(", ")}) without the rest`,
      );
    }
  }
}

/**
 * Applies the store's supersession rules to the new entries before the
 * compaction plans around them, so a malformed reference fails as it would
 * at commit instead of being rebased away: the target must be an earlier
 * `runtime_context` entry on the path (or earlier in the new entries) that
 * is not superseded yet. The committed path already satisfies the rules.
 */
function assertPendingSupersession(
  head: ContextHead,
  path: readonly ContextEntryInput[],
  pending: readonly ContextEntryInput[],
): void {
  const kinds = new Map<string, ContextEntryInput["kind"]>();
  const superseded = new Set<string>();
  for (const entry of path) {
    kinds.set(entry.key, entry.kind);
    if (entry.kind === "runtime_context" && entry.supersedes !== undefined) {
      superseded.add(entry.supersedes);
    }
  }
  for (const entry of pending) {
    if (entry.kind === "runtime_context" && entry.supersedes !== undefined) {
      const target = entry.supersedes;
      if (kinds.get(target) !== "runtime_context" || superseded.has(target)) {
        throw new ContextLogConflictError("invalid_supersession", {
          head,
          message: `Entry "${entry.key}" supersedes "${target}", which is not an active runtime context entry earlier on the path`,
        });
      }
      superseded.add(target);
    }
    kinds.set(entry.key, entry.kind);
  }
}

/**
 * Re-appended entries in order, with every `supersedes` that no longer has
 * a target on the child's path dropped (and any retraction of one removed).
 * Every reference was validated first, so a missing target is always one
 * the compaction left out.
 */
function rebaseSupersession(
  inherited: readonly ContextEntryInput[],
  entries: readonly ContextEntryInput[],
): ContextEntryInput[] {
  const onPath = new Set(inherited.map((entry) => entry.key));
  const rebased: ContextEntryInput[] = [];
  for (const entry of entries) {
    if (
      entry.kind === "runtime_context" &&
      entry.supersedes !== undefined &&
      !onPath.has(entry.supersedes)
    ) {
      if (entry.retraction === true) continue;
      const { supersedes: _target, ...current } = entry;
      rebased.push(current);
    } else {
      rebased.push(entry);
    }
    onPath.add(entry.key);
  }
  return rebased;
}

/**
 * Maps each message the context manager returned to the view message it
 * keeps, or `undefined` for a new message (the summary).
 *
 * Kept messages are recognised by identity only: a manager returns the
 * messages it keeps unchanged, as the built-in one does. Matching by content
 * could take a summary whose text equals an earlier message (such as a
 * previous summary) for a kept message and drop it.
 */
function mapKept(
  view: readonly ModelMessage[],
  kept: readonly ModelMessage[],
): Array<number | undefined> {
  const byIdentity = new Map<ModelMessage, number>();
  view.forEach((message, index) => {
    byIdentity.set(message, index);
  });
  return kept.map((message) => byIdentity.get(message));
}

/**
 * Creates the log-mode compactor for an agent with a context manager.
 *
 * @internal
 */
export function createLogCompactor(
  compactIfNeeded: MessageRuntime["compactMessagesIfNeeded"],
  /**
   * Whether a hypothetical child would still ask for compaction: `view` is
   * its compaction view (what a policy sees), `budgetMessages` its projected
   * request, budgeted on its estimate alone (the last request's measured
   * usage describes the unpruned request). A prune-only child (no summary)
   * is declared only when it would not, so it is not declared on every turn.
   */
  wouldCompact: (view: ModelMessage[], budgetMessages: ModelMessage[]) => boolean,
): LogCompactor {
  return async (input) => {
    const { stream, head, core, path, pending, options } = input;
    if (path.length === 0 || options._skipCompaction) {
      return undefined;
    }

    // An unresolved interrupt blocks the stream (`interrupt_pending`); never
    // compact around a call that is waiting for its resolution.
    if (findUnresolvedInterrupts([...path, ...pending]).length > 0) {
      return undefined;
    }
    assertPendingSupersession(head, path, pending);

    // The leading run of active runtime context is the unchanged prefix the
    // child inherits. The manager sees it (and the core) as system
    // messages, which it always keeps and never summarises.
    const active = new Set<ContextEntryInput>(activeContextEntries([...path, ...pending]));
    let inheritedCount = 0;
    while (
      inheritedCount < path.length &&
      path[inheritedCount]!.kind === "runtime_context" &&
      active.has(path[inheritedCount]!)
    ) {
      inheritedCount += 1;
    }

    const pairs = pairResolutions(path, active);
    const resolutionOf = new Map([...pairs].map(([resolution, result]) => [result, resolution]));
    const view: ModelMessage[] = [];
    const sources: ViewSource[] = [];
    if (core !== "") {
      view.push({ role: "system", content: core });
      sources.push({ kind: "core" });
    }
    // Under append-only supersession the request also carries every
    // superseded entry and retraction, so the manager counts them (as
    // system messages, never summarised); the child drops them.
    const appendOnly = input.contract[SUPERSESSION_CONTRACT_KEY] === "append";
    const rendered = appendOnly ? appendOnlyRuntimeTexts([...path, ...pending]) : [];
    const pushSuperseded = (index: number) => {
      view.push({ role: "system", content: rendered[index]! });
      sources.push({ kind: "superseded" });
    };
    path.forEach((entry, index) => {
      if (!active.has(entry)) {
        if (appendOnly) pushSuperseded(index);
        return;
      }
      if (pairs.has(index)) return;
      const resolution = resolutionOf.get(index);
      if (resolution !== undefined && entry.kind === "tool_result") {
        const paired = path[resolution] as Extract<ContextEntryInput, { kind: "tool_result" }>;
        view.push({
          role: "tool",
          content: [...paired.message.content, ...entry.message.content],
        });
        sources.push({ kind: "path", index, resolution });
        return;
      }
      view.push(viewMessage(entry));
      sources.push({ kind: entry.kind === "runtime_context" ? "runtime" : "path", index });
    });
    pending.forEach((entry, index) => {
      if (active.has(entry)) {
        view.push(viewMessage(entry));
        sources.push({ kind: "pending", index });
      } else if (appendOnly) {
        pushSuperseded(path.length + index);
      }
    });

    const runId = options._runId ?? "run";
    // The head's path is immutable, so its reference and the new input
    // identify the source exactly.
    const sourceDigest = sha256Hex(
      canonicalContextJson({
        versionId: head.versionId,
        entryCount: head.entryCount,
        pending: [...pending],
      }),
    );
    const contextLog: CompactionContextLog = {
      runId,
      stream,
      sourceDigest,
      summaryStream: {
        threadId: stream.threadId,
        branchId: stream.branchId,
        streamId: `${runId}/summary/${sourceDigest}`,
      },
    };
    const compactOptions: CompactOptions = {
      contextLog,
      ...(options.signal && { signal: options.signal }),
    };
    // The budget is the request the model would be sent (LLE-14056); the
    // view is what the manager keeps or summarises.
    const budgetMessages = await input.project([...path, ...pending]);
    const outcome = await compactIfNeeded(
      view,
      options,
      stream.threadId,
      compactOptions,
      budgetMessages,
    );
    if (!outcome.compacted) {
      return undefined;
    }

    // The conversation entries the manager kept, and the new messages it
    // returned (the summary). The runtime places everything: the prefix,
    // then the summary, then the kept entries in path order, then the new
    // input.
    const summary: ContextEntryInput[] = [];
    const retained = new Set<number>();
    mapKept(view, outcome.messages).forEach((viewIndex, at) => {
      if (viewIndex !== undefined) {
        const source = sources[viewIndex]!;
        if (source.kind === "path") {
          retained.add(source.index);
          if (source.resolution !== undefined) retained.add(source.resolution);
        }
        return;
      }
      const message = outcome.messages[at]!;
      const key = `${input.keyPrefix}:summary:${summary.length}`;
      // A summary is prose. A tool part in a new message is a copy of a kept
      // call or result, whose pairing with the source entries is lost.
      if (
        Array.isArray(message.content) &&
        message.content.some((part) => part.type.startsWith("tool-"))
      ) {
        throw new ContextLogInvalidError(
          "compaction_invalid_summary",
          "Compaction produced a new message with tool parts; return kept messages unchanged and a summary without tool calls or results",
        );
      }
      if (message.role === "assistant") {
        summary.push({ kind: "assistant", key, message });
      } else if (message.role === "user") {
        summary.push({ kind: "user", key, message });
      } else {
        throw new ContextLogInvalidError(
          "compaction_invalid_summary",
          `Compaction produced a new "${message.role}" message; a summary must be a user or assistant message`,
        );
      }
    });

    // A tool group is kept whole when the manager kept any of it (or it
    // reaches the new input). The view already lets the built-in retention
    // keep a resolution with its call's block; this also covers other
    // managers and a resolution without a result yet.
    const groups = toolGroups([...path, ...pending]);
    const keptGroups = new Set<number>();
    groups.forEach((group, index) => {
      if (group !== undefined && (index >= path.length || retained.has(index))) {
        keptGroups.add(group);
      }
    });
    path.forEach((_entry, index) => {
      const group = groups[index];
      if (group !== undefined && keptGroups.has(group)) retained.add(index);
    });

    // Progress: if every conversation entry is still kept (nothing was
    // summarised, or the groups brought back all that was), a child would
    // only add a summary to the same entries. Without a summary, a child
    // would drop history that nothing summarises. Either way the head's
    // version stays current, and no transition is declared, unless the
    // request carries superseded entries (append-only supersession): then a
    // child that keeps every conversation entry, without a summary, still
    // drops them.
    const compactable = sources.filter((source) => source.kind === "path");
    const keptAll = compactable.every(
      (source) =>
        retained.has(source.index) &&
        (source.resolution === undefined || retained.has(source.resolution)),
    );
    const prunable = appendOnly && path.some((entry) => !active.has(entry));
    if (keptAll ? !prunable : summary.length === 0) {
      return undefined;
    }
    const kept = keptAll ? [] : summary;

    // The summary is new content: screen it like any other new input.
    const screened = kept.length > 0 ? await input.screen(kept) : [];
    if (
      screened.length !== kept.length ||
      screened.some((entry, index) => entry.kind !== kept[index]!.kind)
    ) {
      throw new ContextLogInvalidError(
        "compaction_invalid_summary",
        "Screening the compaction summary must keep its entries",
      );
    }
    const tail = path.filter(
      (entry, index) =>
        index >= inheritedCount &&
        active.has(entry) &&
        (entry.kind === "runtime_context" || retained.has(index)),
    );

    const prefix = path.slice(0, inheritedCount);
    const append = rebaseSupersession(prefix, [...screened, ...tail, ...pending]);
    const entries = [...prefix, ...append];
    assertToolGroupsKept([...path, ...pending], entries);
    // A prune-only child is progress only when it brings the request back
    // under budget. Otherwise the next turn's superseded entry would ask
    // for it again, and a compaction (a cache break) would follow every
    // turn while the conversation stays inside the keep window.
    if (kept.length === 0) {
      const childView: ModelMessage[] = [
        ...(core === "" ? [] : [{ role: "system" as const, content: core }]),
        ...entries.map(viewMessage),
      ];
      if (wouldCompact(childView, await input.project(entries))) return undefined;
    }

    return {
      transition: {
        reason: "compaction",
        parent: { versionId: head.versionId, inheritedCount },
        core,
        contract: { ...input.contract },
      },
      append,
      entries,
    };
  };
}
